### ISSUE TITLE
Bootstrap fails on Mac, atom-package-manager/bin/node: No such file or directory

### ISSUE THREAD

**Issue by nantas** [atom-archive/electron-starter#24]
The bootstrap script trying to find `atom-shell-starter/apm/node_modules/atom-package-manager/bin/node` but couldn't.

``` bash
firebox-nantas:atom-shell-starter nantas$ node script/bootstrap
Node: v0.10.31
npm: v1.4.28
Installing build modules...
npm WARN unmet dependency /Users/nantas/projects/Testing/atom-shell-starter/build/node_modules/grunt requires async@'~0.1.22' but will load
npm WARN unmet dependency /Users/nantas/projects/Testing/atom-shell-starter/build/node_modules/async,
npm WARN unmet dependency which is version 0.2.10
npm WARN unmet dependency /Users/nantas/projects/Testing/atom-shell-starter/build/node_modules/grunt-bower-task requires rimraf@'~2.0.2' but will load
npm WARN unmet dependency /Users/nantas/projects/Testing/atom-shell-starter/build/node_modules/rimraf,
npm WARN unmet dependency which is version 2.2.8
npm WARN unmet dependency /Users/nantas/projects/Testing/atom-shell-starter/build/node_modules/grunt-bower-task requires async@'~0.1.22' but will load
npm WARN unmet dependency /Users/nantas/projects/Testing/atom-shell-starter/build/node_modules/async,
npm WARN unmet dependency which is version 0.2.10
Installing apm...
/Users/nantas/projects/Testing/atom-shell-starter/apm/node_modules/atom-package-manager/bin/apm: line 40: /Users/nantas/projects/Testing/atom-shell-starter/apm/node_modules/atom-package-manager/bin/node: No such file or directory
```

**Comment by mcolyer** [comment]
Running on 82dd2eb0f865e4508cda42f9316ce6773df0b751 with the versions below works for me:

```
v0.10.35
1.4.28
/Users/<user>/.nodenv/shims/node
```

**Comment by fxdgear** [comment]
I get the following error:
```
± node script/bootstrap
Node: v0.12.0
npm: v1.4.28
Installing build modules...
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/nicklang/develop/boss-client/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/nicklang/develop/boss-client/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

/Users/nicklang/develop/boss-client/apm/node_modules/atom-package-manager/bin/apm: line 40: 82426 Trace/BPT trap: 5       "$binDir/$nodeBin" --harmony_collections "$binDir/../lib/cli.js" "$@"
```

**Comment by paulcbetts** [comment]
@fxdgear You're using node 0.12.x, at the moment you need to use node 0.10.x

**Comment by fxdgear** [comment]
Ahh ok thanks.

**Comment by jyu-rmn** [comment]
What is the main reason it works on 0.10.x, but not 0.12.x?

**Comment by tommoor** [comment]
I also get this error with the following setup:

```
v0.10.33
2.1.11
/usr/local/bin/node
```

**Comment by paulcbetts** [comment]
> What is the main reason it works on 0.10.x, but not 0.12.x?

I just haven't updated it yet - I'll probably do this soon

**Comment by jplatte** [comment]
I get the same error message when trying to build atom 0.190.0 on arch linux. Previous versions worked.

**Comment by paulcbetts** [comment]
![](http://cl.ly/image/39032b2S0x3M/content#png)

**Comment by jplatte** [comment]
Okay, maybe I am wrong here and using Atom doesn't mean using 'atom-shell-starter'. But if this error is not about a seperate program, then I'm pretty sure the node version is not the problem. I have node 0.12 installed since before Atom supported it (v0.181.0 failed to build because of that, then v0.182.0 fixed that), and it seems @tommoor also reproduce this issue with node 0.10.

**Comment by paulcbetts** [comment]
@jplatte Ah! No, this repo has nothing to do with building Atom the text editor, sorry. You need to go to atom/atom

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
